Schwiftology/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/links', to: 'links#index'
  get '/new', to: 'links#new'
  get '/about', to: 'pages#about'
  
  resources :links

  root to: "pages#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Schwiftology/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Schwiftology/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

Schwiftology/app/models/link.rb
class Link < ApplicationRecord

  belongs_to :user
  has_many :comments, as: :commentable
end

Schwiftology/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links       
end

Schwiftology/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Schwiftology/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :find_commentable

    def new
      @comment = Comment.new
    end

    def create
      @comment = @commentable.comments.new comment_params

      if @comment.save
        redirect_to :back, notice: 'Your comment was successfully posted!'
      else
        redirect_to :back, notice: "Your comment wasn't posted!"
      end
    end

    private

    def comment_params
      params.require(:comment).permit(:body)
    end

    def find_commentable
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      @commentable = Story.find_by_id(params[:story_id]) if params[:story_id]
    end

end

Schwiftology/app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)
    @link = @commentable.link.new comment_params
    
    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user

    redirect_to :back
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user

    redirect_to :back

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

Schwiftology/app/controllers/pages_controller.rb
class PagesController < ApplicationController
 def home
 end

 def about
 end
 
end

Schwiftology/app/helpers/application_helper.rb
module ApplicationHelper
end

Schwiftology/app/helpers/links_helper.rb
module LinksHelper
end

Schwiftology/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schwiftology</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="background-img">

  <% flash.each do |name, msg| %>
     <% content_tag(:div, msg, class: "alert alert-#{name}") %>
     <% end %>
     <%= render 'shared/navbar' %>
     <div id="main-container" class="main-container">
       <div class="text-center">
         <%= yield %>
       </div>
      </div>


     <%= render 'shared/footer' %>

  </body>
</html>

Schwiftology/app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



        <form role="form">
          <div class="field form-group">
            <%= form.label :title %>
            <%= form.text_field :title, id: :link_title %>
          </div>



          <div class="field form-group">
            <%= form.label :url %>
            <%= form.text_field :url, id: :link_url %>
          </div>



          <div class="actions">
            <%= form.submit %>
          </div>
        </form>




<% end %>

Schwiftology/app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

Schwiftology/app/views/links/index.html.erb
<h1>Links</h1>

      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Url</th>
            <th colspan="3"></th>
          </tr>
        </thead>


          <tbody>
            <% @links.each do |link| %>
              <tr>
                <td><%= link.title %></td>
                <td><%= link.url %></td>
                <td><%= link_to 'Show', link %></td>
                <% if link.user == current_user %>
                <td><%= link_to 'Edit', edit_link_path(link) %></td>
                <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
               <% end %>
                </tr>
            <% end %>
          </tbody>

      </table>

Schwiftology/app/views/links/new.html.erb
<div class="container">
  <div class="row">
    <div class="text-center col-md-3">
     <h1>New Link</h1>
    </div>
  </div>
</div>


        <%= render 'form', link: @link %>

        <%= link_to 'Back', links_path %>

Schwiftology/app/views/links/show.html.erb
      <p id="notice"><%= notice %></p>
      <div class="main-container">
        <div class="row">
          <div class="col-4 text-center">
            <p>
            <strong>Title:</strong>
            <%= @link.title %>
            </p>
          </div>
        </div>
          <div class="row">
            <div class="col-4 text-center">
              <p>
                <strong>Url:</strong>
                <%= @link.url %>
              </p>

              <%= link_to 'Edit', edit_link_path(@link) %> |
              <%= link_to 'Back', links_path %>

              <%= f.text_area :body, placeholder: "Add a comment" %><br/>
              <%= f.submit "Add Comment" %>
        <% end %>

        <ul>
          <%= render(partial: 'comments/comment', collection: @story.comments) %>
        </ul>
      </div>
    </div>
  </div>

Schwiftology/app/views/pages/about.html.erb
<div class="main-container">


<div id="dinner" class="container">
    <div class="row">
      <div class="lg-col-11 md-col-11 sm-col-11">
        <%= image_tag("about/dinner.png") %>
      </div>
    </div>
  </div>

  <div id="title" class="container">
    <div class="row">
      <div class="col-4 text-center ">
      <a href="https://fontmeme.com/fonts/get-schwifty-font/"><img src="https://fontmeme.com/permalink/180112/8c10cea8856a8ab50639495229328fb2.png" alt="get-schwifty-font" border="0"></a>
      </div>
    </div>
  </div>


    <div class="container">
      <div class="row">
        <div class="col-9 text-center">
          <p>
            Schwiftology is a twenty-first-century religion that teaches us the truth of the
            reality of the universe around us and the absurdity of having a singular purpose.<br>
            We follow the Adventures of Rick & Morty as Parables to explain the truth of our existence.
            Praise to the words of the one True Morty <br>
            "Nobody exists on purpose, nobody belongs anywhere, everybody's gonna die; come watch TV."
          </p>
        </div>
      </div>
    </div>
</div>

Schwiftology/app/views/pages/home.html.erb
<div class="banner">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div id="banner-img" class="banner-content">

                  <%= image_tag("home/123.jpg") %>

                    <ul class="buttons">
                        <li>
                            <div class="primary-button">
                                <a <%= link_to 'Sign up', new_user_registration_path %></a>
                            </div>
                        </li>
                        <li>
                            <div class="secondary-button">
                                <a <%= link_to 'Sign in', new_user_session_path %></a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<section id="about" class="page-section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div class="service-item first-service">
                    <div class="icon">
                        <img src="img/first-service-icon.png" alt="">
                    </div>
                    <h4>Topic 1</h4>
                    <p> Filler</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="service-item second-service">
                    <div class="icon">
                        <img src="img/second-service-icon.png" alt="">
                    </div>
                    <h4>Topic 2</h4>
                    <p>Filler</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="service-item third-service">
                    <div class="icon">
                        <img src="img/third-service-icon.png" alt="">
                    </div>
                    <h4>Topic 3</h4>
                    <p>Filler</p>
                </div>
            </div>
        </div>
    </div>
</section>


<section id="contact-us">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-heading">
                    <h4>Contact Us</h4>
                    <p>Send us your feedback. :)</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <form id="contact" action="#" method="post">
                    <div class="row">
                        <div class="col-md-6">
                          <fieldset>
                            <input name="name" type="text" class="form-control" id="name" placeholder="Name..." required="">
                          </fieldset>
                        </div>
                        <div class="col-md-6">
                          <fieldset>
                            <input name="email" type="email" class="form-control" id="email" placeholder="Email..." required="">
                          </fieldset>
                        </div>
                         <div class="col-md-6">
                          <fieldset>
                            <input name="subject" type="text" class="form-control" id="subject" placeholder="Subject..." required="">
                          </fieldset>
                        </div>
                        <div class="col-md-6">
                          <fieldset>
                            <input name="phone" type="phone" class="form-control" id="phone" placeholder="Phone..." required="">
                          </fieldset>
                        </div>
                        <div class="col-md-12">
                          <fieldset>
                            <textarea name="message" rows="6" class="form-control" id="message" placeholder="Message..." required=""></textarea>
                          </fieldset>
                        </div>
                        <div class="col-md-12">
                          <fieldset>
                            <button type="submit" id="form-submit" class="btn">Send your message</button>
                          </fieldset>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-6">
                <div id="map">
<!-- How to change your own map point
    1. Go to Google Maps
    2. Click on your location point
    3. Click "Share" and choose "Embed map" tab
    4. Copy only URL and paste it within the src="" field below
-->
                    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d112729.89568016662!2d-82.10863069999998!3d27.999732099999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1515796461545" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
    </div>
</section>

Schwiftology/app/views/shared/_footer.html.erb
<footer>
    <!--Copyright-->
    <div class="footer-copyright">
        <div class="container-fluid">
          <div class="row">
            <div class="text-center mb-3">
            © 2017 Copyright: <a href="#">Schwiftology-2017  </a>
            </div>
          </div>
        </div>
      </div>
    <!--/.Copyright-->
</footer>
<!--/.Footer-->

Schwiftology/app/views/shared/_navbar.html.erb
<!-- Nav Bar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
     <%= image_tag("shared/banner.jpg") %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About Us', about_path %></li>

        <li><%= link_to 'Forum', links_path %></li>
        <li><%= link_to 'Account', edit_user_registration_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
          </ul>
    </div>
  </div>
</nav>